Source/URLDispatcher.spoon/init.lua

List containing optional additional redirection decoders (other than the known Slack decoder, which is enabled by `URLDispatcher.decode_slack_redir_urls` to apply to URLs before dispatching them. Each list element must be a list itself with four elements:
* a name to identify the decoder
* a regex to match against the URL
* a replacement pattern to apply if a match is found.
* (optional) whether to skip URL-decoding of the resulting
string (by default the results are always decoded)

New configuration parameter URLDispatcher.url_redir_decoders

---

Source/WindowScreenLeftAndRight.spoon/init.lua

Length of the animation to use for the window movements across the
screens. `nil` means to use the existing value from
`hs.window.animationDuration`. 0 means to disable the
animations. Default: `nil`.

New parameter WindowScreenLeftAndRight.animationDuration

---

Source/Leanpub.spoon/init.lua

These are produced when, for example, your Leanpub account does not have API-usage rights. Now an appropriate notification is produced.

Leanpub Spoon: Handle "failure" messages

---

Source/ArrangeDesktop.spoon/docs.json
Source/ArrangeDesktop.spoon/init.lua

This spoon arranges the windows on your desktop based on supplied configurations. The `Log Current Desktop Arrangement` menu item builds out the configuration for you and places it in the Hammerspoon console. Once you have one or more configurations, menu items will place the windows appropriately.

Arrange Desktop Spoon

---

Source/AppLauncher.spoon/docs.json
Source/AppLauncher.spoon/init.lua

This pull request adds a new spoon that allows you to launch/focus apps using the modifier key and just a single letter. An example configuration could like this:
```lua
spoon.SpoonInstall:andUse("AppLauncher", {
hotkeys = {
c = "Calendar",
d = "Discord",
f = "Firefox Developer Edition",
n = "Notes",
p = "1Password 7",
r = "Reeder",
t = "Kitty",
z = "Zoom.us",
}
})
```
With this configuration, hitting <kbd>hyper</kbd><kbd>c</kbd> would launch Calendar.app, <kbd>hyper</kbd><kbd>d</kbd> would launch Discord and so forth.
I hope people will find it useful.

Add new spoon for launching apps with hotkeys.

---

Source/MouseFollowsFocus.spoon/init.lua

Prior to this, dragging a non-focused window made it jump to the original
center of the window.

MouseFollowsFocus: fix for dragging non-focused window

---

Source/WinWin.spoon/init.lua

The `hs.screen:fullFrame()` function returns the screen frame _including_ the dock and the menu, whose space cannot be occupied by windows. The end result is that when you use WinWin to put window A to `cornerNE` and window B to `cornerSE`, the lower border of A and the upper border of B overlap with each other.
This PR replaces the `hs.screen:fullFrame()` calls in WinWin with `hs.screen:frame()` to fix this issue.

WinWin: Use hs.screen:frame() instead of hs.screen:fullFrame()

---

Source/ClipboardTool.spoon/init.lua

\u{1f4cb} is Clipboard. The old one is paperclip.
Details: https://codepoints.net/U+1F4CB

ClipboardTool: Fix menubar icon emoji

---

Source/ForceTouchMapper.spoon/docs.json
Source/ForceTouchMapper.spoon/init.lua

Hi,
I have implemented a simple spoon for mapping force clicks in specified apps to key stroke.
The motivation for that was missing support for force click actions in VS Code where it's perfect candidate for invoke a Peek Definition functionality.
Example use:
```
spoon.SpoonInstall:andUse("ForceTouchMapper", {
config = {apps = {["com.microsoft.VSCode"] = {keyStroke = {{"cmd"}, 'y'}}}}
})
```

feat: add ForceTouchMapper spoon

---

Source/BingDaily.spoon/docs.json
Source/BingDaily.spoon/init.lua

Bing offers their picture of the day in UHD resolution as well as HD.
Since Macs have high res Retina displays, add an option to the BingDaily
spoon to download the wallpaper image in UHD resolution.
Tested on Macos 11.6 / Macbook Air, Hammerspoon 0.9.91.

BingDaily: Add option to download image in UHD resolution

---

Source/ArrangeDesktop.spoon/docs.json
Source/ArrangeDesktop.spoon/init.lua

This overhauls the functionality of the Spoon to auto-generate the configuration of your desktop arrangement. This replaces the previous flow of having to select a menu option, open the console, hand copy the config from there into your `init.lua`, and tweak to get it running.

Arrange Desktop 2.0

---

Source/URLDispatcher.spoon/init.lua

```
2021-08-14 22:12:08: *** ERROR: .../qaisjp/.hammerspoon/Spoons/URLDispatcher.spoon/init.lua:97: attempt to index a nil value
stack traceback:
.../qaisjp/.hammerspoon/Spoons/URLDispatcher.spoon/init.lua:97: in function 'URLDispatcher.dispatchURL'
.../qaisjp/.hammerspoon/Spoons/URLDispatcher.spoon/init.lua:157: in function 'hs.urlevent.internal.httpCallback'
(...tail calls...)
[C]: in function 'xpcall'
...n.app/Contents/Resources/extensions/hs/urlevent/init.lua:42: in function <...n.app/Contents/Resources/extensions/hs/urlevent/init.lua:35>
```
Reproduce the issue by:
1. minimising all windows
2. opening iTerm
3. Running `sleep 5 && open 'https://github.com'`
4. Minimising iTerm
5. Clicking on the background (so that “Finder” shows in the menu bar)
6. Waiting for the `open` to run …

URLDispatcher: fix crash when there is no window

---

Source/Seal.spoon/seal_useractions.lua

The api provides a parameter (`sz`) to specify the size of the favicon.
I pushed with value 64, fell free to change it.
Difference:
Unfortunately I could not find any documentation for this api.

Seal: bigger size for favicon

---

Source/MouseFollowsFocus.spoon/init.lua

If a window is moved far enough that the mouse is no longer under it, and the user is not using the mouse, move the mouse.  If another spoon moves a window to another monitor, for example, then the mouse is moved also.
Also, fix use of a deprecated API.

MouseFollowsFocus: Move mouse when a window warps

---

Source/WindowSigils.spoon/coordinate_set.lua
Source/WindowSigils.spoon/empty_window.lua
Source/WindowSigils.spoon/init.lua
Source/WindowSigils.spoon/space_map.lua

This incorporates the commit from #239 (thanks @erbridge) , and #239 should partially fix #238.
In addition, I had some nice improvements that I never submitted that allow stacking windows nicely.  When two windows have the same position:
1. Use the OS window id when sorting to keep the assigned sigils stable. (It used to depend on tab order, and so they would keep moving around).
2. Prevent the sigil indicators themselves from overlapping on the screen.  They are now spaced out nicely so you can select a window as though it were a kind of tabbed control.
For example:
_Not_ a part of this PR, but coming up in hopefully not more than a few weeks:
* Automatically detect added and removed screens.   Right now it fails to draw labels on new screens. (The workaround is to reload the …

WindowSigils: Fixes and support for stacking windows and empty spaces

---

Source/HSearch.spoon/hs_btabs.lua
Source/HSearch.spoon/init.lua

Currently the behavior for (HSearch) browser tabs are:
- (Safari) switch to that tab and reload, or
- (Chrome) open a new tab with the URL.
Changing both to just focusing on the tab in browser. Using javascript to find corresponding tabs with the URL.

HSearch btabs: use tab switch instead of reload/new

---

Source/Seal.spoon/seal_useractions.lua

When typing more than one word when using a `useraction` with `keyword`, both click to choose or pressing ENTER to choose will not open the URL.
Using the `Translate using Leo` as example, typing `leo one` it will work fine and open  the url with the `...?search=one`, but when typing `leo one two` nothing happens.
This will encode the value and escape the `%`.

Seal useractions query encode

---

Source/EjectMenu.spoon/init.lua

Added documentation regarding modifier keys.

---

Source/EmmyLua.spoon/init.lua

add info about pathwatcher to EmmyLua Spoon
note: not updated the `docs.json` because i don't get the `hs.ipc.cliInstall()` working

add info about pathwatcher to EmmyLua Spoon

---

Source/URLDispatcher.spoon/init.lua

Multiple improvements:
- default_handler can now also be a function in addition to a bundle ID.  If a function is given, it is called with the URL.
- In url_patterns, the second value of each element can now be both a string (interpreted as a bundle ID) or a function (called with the URL). A function can also be specified as the third value, for backwards compatibility, so existing configurations should not break.
- In url_patterns, the first value of each element can now be both a string  (a single pattern), a table containing a list of patterns, or a filename from which  the list of patterns to match will be read. Furthermore, a watcher is set  so that the patterns are automatically reloaded if the file changes.
- In url_patterns, the last element of each rule can be an app name pattern …

URLDispatcher: Improvements in patterns and function URL handlers

---

Source/AppWindowSwitcher.spoon/docs.json
Source/AppWindowSwitcher.spoon/init.lua

Application aware, keyboard driven window switcher.
Switches windows by focusing and raising them. All windows matching a bundelID, a list of bundleID's, an application name matchtext, or a list of application name matchtexts are switched by cycling them.

New Spoon: AppWindowSwitcher

---

Source/ClipboardTool.spoon/init.lua

This will show a small preview of large clipboard texts, but the full content is available for searching and pasting.

Truncate preview of large clipboard texts

---

Source/Seal.spoon/seal_useractions.lua

When querying a single word (without spaces), the substitution string `${query}` won't be replaced.
`string.gsub` returns two values: the string with substitutions and the number of substitutions made
If doing the nested `gsub`, these two return values will be passed into the outer `gsub`, which accepts an optional fourth parameter specifying how many substitutions should be made. So the number of substitutions in the inner `gsub` determines the number of substitutions in the outer `gsub`: When the query doesn't contain a blank, that number of substitutions in the inner `gsub` is `0` and the outer `gsub` won't replace anything, leaving `${query}` in the `url`.
By first assigning the `gsub` result to a variable, the number of substitutions return value will be ignored.

Fix query replacement for non-spaced queries

---

Source/TimeMachineProgress.spoon/init.lua

I noticed after I upgraded to Monterey (12.2 or 12.3, not sure when it started) that TimeMacineProgress would sometimes appear to get stuck at the **(prep)** stage. That was being caused by an error - apparently `tmutil status` now reports intermediate phases that lack any Percent value.  This PR addresses that error, bumps the version, and as a bonus provides a little more info in the (prep) tooltip during the various backup phases provided by the apparently modified tmutil's status results. 
FWIW TimeMachineProgress's percentage stops advancing when TimeMachine goes into its 'cleaning up' phases, prior to 'stopping'. Addressing that is a separate issue that I'm not sure is worth the effort. I'm happy to try to help if you think it is.
Below is an example of the tmutil status data that …

address Monterey changes causing TimeMachineProgress to error

---

Source/ArrangeDesktop.spoon/init.lua

Fixes a typo in the dialog message showing before recording of app windows in the ArrangeDesktop spoon

Fix createArrangement dialog msg [spoon.ArrangeDesktop]

---

Source/Seal.spoon/init.lua

Seal plugins can define a table of commands which contains
the command used to launch it in the `cmd` field.
However currently the key of the command in the commands table
is used instead of this field.
This was identical for most seal plugin except filesearch which
uses the special ' character as the command trigger.

fix seal plugins cmd being ignored in commands table

---

Source/EmmyLua.spoon/init.lua

save timestamps in to a file `timestamps.json` to check if `docs.json` are changed.
if not changed then skip the file check
add also a check to skip the writing to `timestamps.json`

EmmyLua: save timestamps of docs.json to skip if no change

---

Source/AClock.spoon/init.lua

AClock tries to display the clock in the center of the screen, but if monitors are plugged in, or the resolution changes, this calculation is no longer correct.
This PR adds a screen watcher to recalculate the frame when the displays change.

Make AClock recalculate canvas on screen change

---

Source/PaperWM.spoon/init.lua

This is a scrolling tiled window manager. It provides mostly the same functionality for MacOS as the PaperWM Gnome extension does for Linux.
Myself and a small group of people have been using this Spoon daily at https://github.com/mogenson/PaperWM.spoon for awhile. I think it has reached enough stability to be incorporated into the offical Hammerspoon Spoons repo.

Add PaperWM.spoon

---

Source/InputMethodIndicator.spoon/docs.json
Source/InputMethodIndicator.spoon/init.lua

Show input method indicator in the current mouse position.
It shows a small but noticable dot near the cursor.
It can be very useful when you are using a non-ABC input method and often needs to switch between ABC and the non-ABC input method.
For example, it lights a green dot when you're using ABC input method while lighting red when typing with Pinyin in Chinese.
Hammerspoon helps me a lot in my daily working and I am showing great interest exploring new usages. If there are any error or anything needs to be improved, feel free to note it. Thanks very much!

Add InputMethodIndicator.spoon

---

Source/Keychain.spoon/init.lua

Issue #311  - Keychain method not called addItem and adds “-w” to service 
Renamed `addPassword` back to `addItem `
Removed the  concatenation of the `cmd` string that added the password string and flag a second time. 
At the same time removing the issue of the missing space which was malforming other options.
The function now works as per the documentation.

Issue #311  - Fixed Keychain addItem 

---

Source/CountDown.spoon/init.lua
Source/CountDown.spoon/readme.org

- Improved configuration of the notification area (size and transparency)
- Added optional icons in the menubar to start, pause and end the time, and notify of remaining time
- It is now able to deal with suspending the laptop during the timer i.e. time runs in "user" time, not "computer running" time
- added hotkeys
- able to call timer again with last period
- or set new period

Improved CountDown timer

---

Source/PaperWM.spoon/docs.json
Source/PaperWM.spoon/init.lua

Update PaperWM from the upstream source at
https://github.com/mogenson/PaperWM.spoon
Changes include:
- floating layer
- untile windows on exit
- fix move window to space and focus space
- warn about unsupported tabs
- change default hotkeys
- watch screens for changes
- switch to left or right space
- reverse cycle window widths
- customize window ratios

PaperWM update v0.4 -> v0.5

---

Source/Commander.spoon/init.lua
docs/Commander.html
docs/docs.json

fix typo and name
commandderCommandTable -> commanderCommandList

fix typo and name commandderCommandTable -> commanderCommandList

---

Source/RecursiveBinder.spoon/init.lua

The logic for dividing the helper into a specific number of columns was broken. This solution also circumvents the need for a regex to remove unnecessary whitespace.

fix formatting problem with RecursiveBinder.showBindHelper()

---

Source/CountDown.spoon/init.lua

if the number of pixels to advance per second was larger than one a non-existing function was being called. This has been addressed.
Addresses #325
Also, removed spurious debugging print.

Properly draw progress bar when timer advances
